import Image from "next/image"; import Link from "next/link"; import { ArrowDown, ArrowRight } from "lucide-react";
import { categories, products } from "@/lib/data"; import { ProductCard } from "@/components/product-card";
export default function Home(){return <main>
 <section className="image-noise relative min-h-[100svh] overflow-hidden bg-ink text-white"><Image src="/images/northline-hero.png" alt="Northline campaign" fill priority className="object-cover object-[63%_center] opacity-90"/><div className="absolute inset-0 bg-gradient-to-r from-black/55 via-black/5 to-black/20"/><div className="container-x relative z-10 flex min-h-[100svh] flex-col justify-end pb-8 pt-28"><div className="eyebrow mb-5 flex items-center gap-3 text-white/75"><span className="h-px w-10 bg-current"/>Fall / Winter 2026</div><h1 className="display text-[clamp(52px,13.5vw,210px)]">Northline</h1><div className="mt-5 flex flex-col gap-7 border-t border-white/35 pt-5 md:flex-row md:items-end md:justify-between"><p className="max-w-sm text-sm leading-6 text-white/75">Modern essentials built for everyday movement. Designed with restraint. Made to endure.</p><div className="flex gap-3"><Link className="btn-light" href="/shop">Shop collection <ArrowRight size={15}/></Link><Link className="btn-outline border-white text-white" href="#collection">Explore</Link></div></div></div><a href="#collection" className="absolute right-8 top-1/2 z-20 hidden -translate-y-1/2 flex-col items-center gap-3 text-[9px] uppercase tracking-[.2em] md:flex">Scroll <ArrowDown size={15}/></a></section>
 <section id="collection" className="container-x section-y"><div className="mb-12 flex items-end justify-between"><div><div className="eyebrow mb-5 text-black/45">01 / New collection</div><h2 className="display text-[clamp(50px,8vw,120px)]">Cold form<br/>Series 01</h2></div><Link className="link-line hidden text-xs font-bold uppercase tracking-[.15em] md:block" href="/shop">View all products ↗</Link></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-4 md:gap-x-5">{products.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></section>
 <section className="bg-ink py-5 text-white overflow-hidden"><div className="display whitespace-nowrap text-[clamp(70px,12vw,190px)] text-white/95">FORM / FUNCTION / MOVEMENT / FORM / FUNCTION /</div></section>
 <section className="container-x section-y"><div className="mb-10 flex items-end justify-between"><div><div className="eyebrow mb-4 text-black/45">02 / Shop by form</div><h2 className="display text-[clamp(48px,8vw,110px)]">Categories</h2></div></div><div className="grid gap-4 md:grid-cols-12">{categories.map((c,i)=><Link href={`/categories/${c.slug}`} key={c.slug} className={`card-image group relative overflow-hidden bg-fog ${i<2?"md:col-span-6 aspect-[4/5] md:aspect-[5/4]":"md:col-span-4 aspect-[4/5]"}`}><Image src={c.image} alt={c.name} fill className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white md:p-7"><div className="eyebrow mb-3 text-white/60">0{i+1}</div><div className="display text-[clamp(32px,4vw,58px)]">{c.name}</div><p className="mt-2 max-w-xs text-xs text-white/65">{c.copy}</p></div><ArrowRight className="absolute right-6 top-6 text-white transition group-hover:translate-x-1"/></Link>)}</div></section>
 <section className="container-x pb-24"><div className="mb-10 border-b hairline pb-6"><div className="eyebrow mb-4 text-black/45">03 / Most wanted</div><h2 className="display text-[clamp(45px,7vw,96px)]">Daily rotation</h2></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-4 md:gap-5">{products.slice(8,16).map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></section>
 <section id="story" className="grid bg-[#c9c5bb] md:grid-cols-2"><div className="relative min-h-[70vh]"><Image src="/images/hoodie-editorial.png" alt="Northline atelier" fill className="object-cover"/></div><div className="flex flex-col justify-between p-7 md:p-14 lg:p-20"><div className="eyebrow">04 / Our perspective</div><div className="py-20"><h2 className="display text-[clamp(48px,7vw,100px)]">Less,<br/>but better.</h2><p className="mt-8 max-w-md text-sm leading-7 text-black/65">NORTHLINE studies the space between technical performance and everyday ritual. Each piece is developed slowly: purposeful silhouettes, responsible materials and construction that improves with wear.</p></div><div className="grid grid-cols-3 gap-5 border-t border-black/25 pt-5 text-[10px] uppercase tracking-[.12em]"><span>01<br/><b className="mt-2 block text-lg">Purpose</b></span><span>02<br/><b className="mt-2 block text-lg">Material</b></span><span>03<br/><b className="mt-2 block text-lg">Longevity</b></span></div></div></section>
 <section className="container-x section-y text-center"><div className="eyebrow mb-7 text-black/45">Private list / No noise</div><h2 className="display mx-auto max-w-5xl text-[clamp(48px,8vw,120px)]">Stay in the<br/>North loop</h2><p className="mx-auto mt-7 max-w-md text-sm text-black/55">Early access, studio notes and considered releases. One useful email at a time.</p><form className="mx-auto mt-9 flex max-w-lg border-b border-black"><input required type="email" className="min-w-0 flex-1 bg-transparent py-4 text-sm outline-none" placeholder="Email address"/><button className="text-[10px] font-bold uppercase tracking-[.15em]">Subscribe →</button></form></section>
 </main>}
