"use client";
import Image from "next/image";import { Heart, Minus, Plus, Ruler, ShieldCheck, Star, Truck } from "lucide-react";import { useState } from "react";import { toast } from "sonner";
import type { Product } from "@/lib/types";import { formatPrice } from "@/lib/data";import { useShopStore } from "@/store/use-shop-store";
export function ProductDetail({product}:{product:Product}){const [size,setSize]=useState("M"),[color,setColor]=useState("Black"),[active,setActive]=useState(0);const add=useShopStore(s=>s.addToCart),toggle=useShopStore(s=>s.toggleFavorite),fav=useShopStore(s=>s.favorites.some(i=>i.id===product.id));return <div className="grid md:grid-cols-[1.35fr_.65fr]">
 <div className="bg-[#d8d5cd] md:grid md:grid-cols-2">{product.images.concat(product.images).slice(0,4).map((src,i)=><button key={i} onClick={()=>setActive(i)} className={`relative aspect-[3/4] overflow-hidden border-b border-r border-black/10 ${active===i?"ring-1 ring-inset ring-black":""}`}><Image src={src} alt={`${product.name} view ${i+1}`} fill priority={i===0} className={`object-cover ${i%2?"scale-105 object-[60%_center]":""}`}/></button>)}</div>
 <aside className="px-6 py-10 md:sticky md:top-[72px] md:h-[calc(100vh-72px)] md:overflow-y-auto lg:px-12"><div className="eyebrow text-black/40">{product.category} / NL-{product.id.padStart(4,"0")}</div><h1 className="display mt-5 text-[clamp(44px,5vw,72px)]">{product.name}</h1><div className="mt-6 flex items-center justify-between border-y hairline py-4"><span className="text-lg">{formatPrice(product.price)}</span><span className="flex items-center gap-1 text-xs"><Star size={12} fill="currentColor"/>{product.rating} · 24 reviews</span></div><p className="mt-6 text-sm leading-7 text-black/60">{product.description}</p>
 <div className="mt-9"><div className="mb-3 flex justify-between"><span className="eyebrow">Size — {size}</span><button className="flex gap-1 text-[10px] uppercase"><Ruler size={13}/> Size guide</button></div><div className="grid grid-cols-5 gap-2">{product.sizes.map(s=><button onClick={()=>setSize(s)} className={`h-11 border hairline text-xs ${size===s?"bg-ink text-white":"hover:border-black"}`} key={s}>{s}</button>)}</div></div>
 <div className="mt-7"><div className="eyebrow mb-3">Color — {color}</div><div className="flex gap-3">{product.colors.map(c=><button key={c} onClick={()=>setColor(c)} title={c} className={`size-8 rounded-full border-2 ${color===c?"ring-1 ring-offset-2 ring-black":""}`} style={{background:{Black:"#171717",White:"#f8f7f2",Grey:"#8d8d89",Beige:"#c1ad8c",Navy:"#1e293b"}[c]}}/>)}</div></div>
 <div className="mt-9 grid grid-cols-[1fr_54px] gap-2"><button onClick={()=>{add(product,size,color);toast.success("Added to your bag")}} disabled={!product.stock} className="btn-dark">{product.stock?"Add to bag":"Sold out"}<Plus size={15}/></button><button onClick={()=>{toggle(product);toast(fav?"Removed from saved":"Saved for later")}} className="grid place-items-center border border-black"><Heart size={18} fill={fav?"currentColor":"none"}/></button></div>
 <div className="mt-7 divide-y hairline border-y hairline text-xs">{[[Truck,"Complimentary shipping over $200"],[ShieldCheck,"30-day returns, no questions"],[Minus,"Materials & care"]].map(([Icon,text],i)=>{const I=Icon as typeof Truck;return <div key={i} className="flex items-center gap-3 py-4"><I size={16}/><span>{text as string}</span><Plus className="ml-auto" size={13}/></div>})}</div>
 </aside></div>}
